#
#CC = C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe
#
CC = csc
RM = rm -rf 

all:
	$(CC) /t:exe /out:hello.exe main.cs
	#$(CC) main.c -fPIC -shared -o main.dll
	#$(CC) main.c -fPIC -shared -o main.so
	
clean:
	$(RM) *.exe *.o *.so