#
#CC = D:\mingw_w64\mingw64\bin\gcc.exe
#
CC = gcc
RM = rm -rf 

all:
	$(CC) myifdef.c  -o myifdef
	#$(CC) main.c -fPIC -shared -o main.dll
	#$(CC) main.c -fPIC -shared -o main.so
	
clean:
	$(RM) *.exe *.o *.so