#
#CC = D:\mingw_w64\mingw64\bin\gcc.exe
#
CC = gcc
RM = rm -rf 

all: myextern
	$(CC) myextern.c  -o myextern.exe
	#$(CC) main.c -fPIC -shared -o main.dll
	#$(CC) main.c -fPIC -shared -o main.so
	
clean:
	$(RM) *.exe *.o *.so